### ISSUE TITLE
iOS自动备份一直loading,设备重启后，备份目录重复

### ISSUE THREAD

**Issue by trevorwang12** [wisnuc/New_WisnucBox_iOS#50]
用户使用iOS客户端备份手机内的照片，一直loading，无法开始备份，如下图：
![tim 20171218102104](https://user-images.githubusercontent.com/20084315/34087318-371c0e08-e3dd-11e7-8270-a0de84cdfda2.png)

之后用户重启服务端，再打开iOS客户端，发现手机备份的目录重复，如下图：
![tim 20171218102114](https://user-images.githubusercontent.com/20084315/34087336-5c588a02-e3dd-11e7-9e93-a24398683243.png)

**Comment by CJackYang** [comment]
已修复
